"""Add payment2

Revision ID: 45fb48972a00
Revises: ba6a76c9f293
Create Date: 2023-05-04 12:47:50.860756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fb48972a00'
down_revision = 'ba6a76c9f293'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
