"""Added cinema table 2

Revision ID: 629ae8444c69
Revises: eae724c60622
Create Date: 2023-05-02 15:47:22.443236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629ae8444c69'
down_revision = 'eae724c60622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
