"""Added in rent column status

Revision ID: 85720dd8496e
Revises: d1f252b85996
Create Date: 2023-05-03 10:27:11.299179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85720dd8496e'
down_revision = 'd1f252b85996'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rents', sa.Column('status', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rents', 'status')
    # ### end Alembic commands ###
