"""Add payment 3

Revision ID: a56085c3aa33
Revises: 45fb48972a00
Create Date: 2023-05-04 12:48:21.548401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56085c3aa33'
down_revision = '45fb48972a00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
