"""Add payment

Revision ID: ba6a76c9f293
Revises: 85720dd8496e
Create Date: 2023-05-04 12:46:15.806774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6a76c9f293'
down_revision = '85720dd8496e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
