"""Add payment 4

Revision ID: d947764182f5
Revises: a56085c3aa33
Create Date: 2023-05-04 12:50:08.784562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd947764182f5'
down_revision = 'a56085c3aa33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=125), nullable=True),
    sa.Column('sum_of_favour', sa.Integer(), nullable=True),
    sa.Column('account_check', sa.String(length=50), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rent'], ['rents.id'], name='fk_payments_rents_id_rent'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
